services:
    LSB\UserBundle\Factory\UserFactory: ~

    lsb_user_factory_user:
        alias: 'LSB\UserBundle\Factory\UserFactory'

    LSB\UserBundle\Factory\UserFactoryInterface: '@LSB\UserBundle\Factory\UserFactory'

    LSB\UserBundle\Factory\GroupFactory: ~

    lsb_user_factory_group:
        alias: LSB\UserBundle\Factory\GroupFactory
    LSB\UserBundle\Factory\GroupFactoryInterface: '@LSB\UserBundle\Factory\GroupFactory'

    LSB\UserBundle\Factory\UserGroupFactory: ~
    
    lsb_user_factory_user_group:
        alias: LSB\UserBundle\Factory\UserGroupFactory
    LSB\UserBundle\Factory\UserGroupFactoryInterface: '@LSB\UserBundle\Factory\UserGroupFactory'

