services:
    LSB\UserBundle\Form\UserType:
        tags:
            - { name: form.type }

    LSB\UserBundle\Form\GroupType:
        tags:
            - { name: form.type }

    LSB\UserBundle\Form\UserGroupType:
        tags:
            - { name: form.type }


