services:
    LSB\UserBundle\Manager\UserManager:
        arguments:
            "$objectManager": '@lsb_utility_object_manager'
            "$passwordHasher": '@security.user_password_hasher'

    LSB\UserBundle\Manager\UserGroupManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\UserBundle\Manager\UserGroupRelationManager:
        arguments:
            - '@lsb_utility_object_manager'
