services:
    LSB\UserBundle\Repository\UserRepository:
        arguments:
            - '@doctrine'

    LSB\UserBundle\Repository\UserRepositoryInterface: '@LSB\UserBundle\Repository\UserRepository'

    LSB\UserBundle\Repository\GroupRepository:
        arguments:
            - '@doctrine'
    LSB\UserBundle\Repository\GroupRepositoryInterface: '@LSB\UserBundle\Repository\GroupRepository'

    LSB\UserBundle\Repository\UserGroupRepository:
        arguments:
            - '@doctrine'
    LSB\UserBundle\Repository\UserGroupRepositoryInterface: '@LSB\UserBundle\Repository\UserGroupRepository'
