services:
    LSB\UserBundle\Repository\UserRepository:
        arguments:
            - '@doctrine'

    LSB\UserBundle\Repository\UserRepositoryInterface: '@LSB\UserBundle\Repository\UserRepository'

    LSB\UserBundle\Repository\UserGroupRepository:
        arguments:
            - '@doctrine'
    LSB\UserBundle\Repository\UserGroupRepositoryInterface: '@LSB\UserBundle\Repository\UserGroupRepository'

    LSB\UserBundle\Repository\UserGroupRelationRepository:
        arguments:
            - '@doctrine'
    LSB\UserBundle\Repository\UserGroupRelationRepositoryInterface: '@LSB\UserBundle\Repository\UserGroupRelationRepository'
