language: php

php:
    - 7.4

matrix:
    fast_finish: true
    include:
        - php: 7.4

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

install:
    - composer update --prefer-dist --no-interaction

script:
    # - composer validate --strict --no-check-lock
    - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
