<?php
declare(strict_types=1);

namespace LSB\UserBundle\Form;

use LSB\UtilityBundle\Form\BaseEntityType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class UserType
 * @package LSB\UserBundle\Form
 */
class UserType extends BaseEntityType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add(
                'username', TextType::class
            )
            ->add(
                'plainPassword', TextType::class
            )
            ->add(
                'email', EmailType::class
            );
    }
}
